on: push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static debootstrap
          sudo debootstrap --arch=arm64 jammy /opt/rootfs http://ports.ubuntu.com/ubuntu-ports
      - name: Config rootfs
        run: |
          echo lol
      - name: Build disk image
        run: |
          echo lol
      - name: Tar rootfs
        run: |
          tar -cjvf rootfs.tar.bz2 /opt/rootfs
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Not publishing at this moment"
