on: push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Not publishing at this moment"
